name: CI/CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:

  lint:
    name: Step 1 Lint
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: installation python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: installation requirements, pip & ruff
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: ruff
        run: |
          ruff check .

  tests :
    name: Step 2 Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: installation python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
  
      - name: installation pip, pytest, mypy & radon
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run unit tests
        run: |
          pytest tests/test-api.py