name: CI/CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:

  lint:
    name: Step 1 Lint
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: installation python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: installation requirements, pip & ruff
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: ruff
        run: |
          ruff check .

  tests:
    name: Step 2 Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: installation python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
  
      - name: installation pip, pytest, mypy & radon
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run unit tests
        run: |
          pytest tests/test-api.py

      - name: run db tests
        run: |
          pytest tests/test-db.py

      - name: run benchmarks l√©gers
        run: |
          pytest tests/test-benchmark.py

  docker:
    name: Step 3 Docker
    runs-on: ubuntu-latest
    needs: tests

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: building image and starting services
      run: |
        docker compose build 
        docker compose up -d

    - name: Waiting service started healthy
      run: |
        echo "waiting for service started healthy..."
        timeout 120 bash -c 'until docker compose ps | grep -q "healthy"; do sleep 2; done'
        docker compose ps

    - name: composer down
      if: always()
      run: docker compose down -v
       
  ghcr:
    name: Step 4 ghrc
    needs: docker
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: login ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: metadata for docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/flask-api
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: build and push image docker vers ghrc
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: image docker pushed
        run: |
          echo "image: ghcr.io/${{ github.repository }}:latest"

  kubernetes:
    name: Step 5 kubernetes manifests
    runs-on: ubuntu-latest
    needs: ghcr
  
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        
      - name: installation Kompose
        run: |
          curl -L https://github.com/kubernetes/kompose/releases/download/v1.38.0/kompose-linux-amd64 -o kompose
          chmod +x kompose
          sudo mv kompose /usr/local/bin/

      - name: generate manifests
        run: |
          mkdir -p manifests
          cd manifests
          kompose -f ../docker-compose.yml convert -o .
          ls -la

      - name: deployment package
        run: |
          mkdir -p ShuFirminPython
          cp manifests/* ShuFirminPython/
          ls -la ShuFirminPython/
          zip -r ShuFirminPython.zip ShuFirminPython/
          ls -lh ShuFirminPython.zip

      - name: deploiement
        run: |
          sudo apt-get update
          sudo apt-get install -y lftp
          lftp -c "
            set ftp:ssl-allow yes;
            set ssl:verify-certificate no;
            open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }}
            cd RenduDevopsKube;
            put ShuFirminPython.zip;
            bye
          "