name: CI/CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:

  lint:
    name: Step 1 Lint
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: installation python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: installation requirements, pip & ruff
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: ruff
        run: |
          ruff check .

  tests :
    name: Step 2 Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: installation python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
  
      - name: installation pip, pytest, mypy & radon
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: run unit tests
        run: |
          pytest tests/test-api.py

      - name: run db tests
        run: |
          pytest tests/test-db.py

      - name: run benchmarks l√©gers
        run: |
          pytest tests/test-benchmark.py
  docker :
    needs: tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: login ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: metadata for docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/owner/repo/flask-api
          tags: |
            type=ref,event=branch
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: build and push image docker vers ghrc
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}